### ISSUE TITLE
when i run this.  why does not give me the websides info about phones.

### ISSUE THREAD

**Issue by igotyou22** [la-deep-web/Phoneinfoga#1]
running Numverify.com scan...
[!] An error occured while calling the API (bad request or wrong api key).                                                        
[*] Running OVH scan...                                          
[*] Running OSINT footprint reconnaissance...
[*] Generating scan URL on 411.com...
[*] Would you like to use an additional format for this number ? (y/N) n
[*] ---- Web pages footprints ----
[*] Searching for footprints on web pages... (limit=5)
[!] Request failed. Please retry or open an issue on GitHub.
Traceback (most recent call last):                               
  File "phoneinfoga.py", line 568, in <module>                   
    scanNumber(args.number)                                      
  File "phoneinfoga.py", line 535, in scanNumber                 
    osintScan()                                                  
  File "phoneinfoga.py", line 460, in osintScan                  
    for result in search(req, stop=5):                           
TypeError: 'NoneType' object is not itera

**Comment by koknovem** [comment]
the same issue occurred on kali
