### ISSUE TITLE
bad request or wrong api kkey

### ISSUE THREAD

**Issue by Sidharth-P7** [la-deep-web/Phoneinfoga#12]
!] Request failed. Please retry or open an issue on GitHub.
Traceback (most recent call last):                                                               
  File "/home/sidharth/Phoneinfoga/phoneinfoga.py", line 568, in <module>                        
    scanNumber(args.number)                                                                      
  File "/home/sidharth/Phoneinfoga/phoneinfoga.py", line 535, in scanNumber                      
    osintScan()                                                                                  
  File "/home/sidharth/Phoneinfoga/phoneinfoga.py", line 470, in osintScan                       
    for result in search('intext:"{}" | intext:"{}" ext:doc | ext:docx | ext:odt | ext:pdf | ext:rtf | ext:sxw | ext:psw | ext:ppt | ext:pptx | ext:pps | ext:csv | ext:txt'.format(number,internationalNumber), stop=10):                                                                         
TypeError: 'NoneType' object is not iterable   

**please need reply urgently**

**Comment by MrJyoti** [comment]
🖕🖕🖕
