### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Hiroshy** [la-deep-web/Phoneinfoga#16]
Hola soy nuevo y no se por que me aparece este error, podrias uyudarme por favor
![image](https://user-images.githubusercontent.com/11902774/115971047-ed562080-a50b-11eb-8def-4b750c7eb515.png)

**Comment by bababounty** [comment]
Yes , Traceback error - requests.exceptions.SSLError: HTTPSConnectionPool(host='numverify.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))) 

How to fix this error ?

**Comment by Standardofcare** [comment]
does anyone fixed this error?4

**Comment by wadiim** [comment]
I added the following statement before the line number 291:
```
print("https://numverify.com/php_helper_scripts/phone_api.php?secret_key={}&number={}".format(apiKey, number))
```
and this is the result:
![](https://user-images.githubusercontent.com/33803413/126185314-ece4df6c-3544-420e-9ab6-2d55fafa8f3c.png)

I followed the link and got this:
![](https://user-images.githubusercontent.com/33803413/126185877-473256f8-9793-4dcc-bba9-005562b794a4.png)

Then I created a free account at https://numverify.com and obtained my own API Access Key. I changed the definition of `numverifyScan` function to this:
```python
def numverifyScan():
    global number

    if not args.scanner == 'numverify' and not args.scanner == 'all':
        return -1

    print(code_info + 'Running Numverify.com scan...')

    access_key=MY_ACCESS_KEY
    response = requests.request("GET", "http://apilayer.net/api/validate?access_key={}&number={}".format(access_key, number), data="")

    if response.content == "Unauthorized" or response.status_code != 200:
        print((code_error + "An error occured while calling the API (bad request or wrong api key)."))
        return -1

    data = json.loads(response.content)

    if data["valid"] == False:
        print((code_error + "Error: Please specify a valid phone number. Example: +6464806649"))
        sys.exit()

    InternationalNumber = '({}){}'.format(data["country_prefix"], data["local_format"])

    print((code_result + "Number: ({}) {}").format(data["country_prefix"],data["local_format"]))
    print((code_result + "Country: {} ({})").format(data["country_name"],data["country_code"]))
    print((code_result + "Location: {}").format(data["location"]))
    print((code_result + "Carrier: {}").format(data["carrier"]))
    print((code_result + "Line type: {}").format(data["line_type"]))

    if data["line_type"] == 'landline':
        print((code_warning + "This is most likely a landline, but it can still be a fixed VoIP number."))
    elif data["line_type"] == 'mobile':
        print((code_warning + "This is most likely a mobile number, but it can still be a VoIP number."))
```

Note that you need to replace `MY_ACCESS_KEY` by your own access key in the previous code snippet.

Here is the result:
![](https://user-images.githubusercontent.com/33803413/126188176-9e647f17-299c-4369-8fec-65d094255af3.png)

Hope it helps.

**Comment by Andrejki** [comment]
```
[*] Running local scan...
Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe28b9a4310>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/381 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe28b9a4310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 521, in scanNumber
    localScan(InputNumber)
  File "phoneinfoga.py", line 238, in localScan
    countryRequest = json.loads(requests.request('GET', 'https://restcountries.eu/rest/v2/callingcode/{}'.format(numberCountryCode.replace('+', ''))).content)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  Same error.
  
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/381 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe28b9a4310>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
