### ISSUE TITLE
there is no file called requirement.txt

### ISSUE THREAD

**Issue by priya-kumari-04** [la-deep-web/Phoneinfoga#17]
┌──(root💀kali)-[~/PhoneInfoga]
└─# python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
                                                                                                                      
┌──(root💀kali)-[~/PhoneInfoga]
└─# ls                                                                                                            1 ⨯
api     cmd         config      docs    go.sum   main.go     PhoneInfoga  scanners  utils
client  CODEOWNERS  Dockerfile  go.mod  LICENSE  mkdocs.yml  README.md    support
                                                                                                                      
┌──(root💀kali)-[~/PhoneInfoga]
└─# --help          
--help: command not found

**Comment by wadiim** [comment]
In the installation section in `README.md` there is a URL that leads to another version of this project written in Go. The `requirements.txt` is Python specific so there is no such file. Try to clone this project like this: `git clone https://github.com/la-deep-web/Phoneinfoga.git`

**Comment by Abhimanyudev7** [comment]
use

git clone https://github.com/la-deep-web/Phoneinfoga

**Comment by Andrejki** [comment]
> use
> 
> git clone https://github.com/la-deep-web/Phoneinfoga

Thanks, but then you get this error:

```
[*] Running local scan...
Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe28b9a4310>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/381 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe28b9a4310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 521, in scanNumber
    localScan(InputNumber)
  File "phoneinfoga.py", line 238, in localScan
    countryRequest = json.loads(requests.request('GET', 'https://restcountries.eu/rest/v2/callingcode/{}'.format(numberCountryCode.replace('+', ''))).content)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/381 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe28b9a4310>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by Yohan501** [comment]
> use
> 
> git clone https://github.com/la-deep-web/Phoneinfoga

Then you get this error 



```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Phoneinfoga/phoneinfoga.py", line 92, in <module>
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'
```
