### ISSUE TITLE
Last step error showing me 

### ISSUE THREAD

**Issue by elvishbhai1** [la-deep-web/Phoneinfoga#23]
~/Phoneinfoga $ python phoneinfoga.py -n (+91phonenumber)
    ___ _                       _____        __
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/
 PhoneInfoga Ver. v1.0.0-rc2
 Coded by Charon IV

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Phoneinfoga/phoneinfoga.py", line 92, in <module>
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'

**Comment by Aridlvory** [comment]
For me too..

**Comment by Yohan501** [comment]
> ~/Phoneinfoga $ python phoneinfoga.py -n (+91phonenumber)
>     ___ _                       _____        __
>    / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _
>   / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
>  / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
>  \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
>                                                       |___/
>  PhoneInfoga Ver. v1.0.0-rc2
>  Coded by Charon IV
> 
> 
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/home/Phoneinfoga/phoneinfoga.py", line 92, in <module>
>     requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'

Same bro I got this 


```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Phoneinfoga/phoneinfoga.py", line 92, in <module>
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'
```
