### ISSUE TITLE
NoneType is not iterable for OSINT ++ numverify fails.

### ISSUE THREAD

**Issue by thearctiic** [la-deep-web/Phoneinfoga#5]
[*] Searching for documents... (limit=10)
[*] ---- Reputation footprints ----
[*] Searching for reputation report on whosenumber.info...
[!] Request failed. Please retry or open an issue on GitHub.
Traceback (most recent call last):
  File "phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 535, in scanNumber
    osintScan()
  File "phoneinfoga.py", line 476, in osintScan
    osintReputationScan()
  File "phoneinfoga.py", line 394, in osintReputationScan
    for result in search(dorkRequest, stop=dork['stop']):
TypeError: 'NoneType' object is not iterable

and

[*] Running Numverify.com scan...
[!] An error occured while calling the API (bad request or wrong api key).
[*] Running OVH scan...

Fix?

**Comment by x3rxe5** [comment]
### Same Issue Occurred

here I have attached the same issue and I got in Linux with the python3 version
```
[!] Request failed. Please retry or open an issue on GitHub.
Traceback (most recent call last):
  File "phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 535, in scanNumber
    osintScan()
  File "phoneinfoga.py", line 460, in osintScan
    for result in search(req, stop=5):
TypeError: 'NoneType' object is not iterable

```
